[profile.release]
debug = true
codegen-units = 1

[workspace]
members = [
    "cdt",
    "express",
    "step",
    "gui",
    "nurbs",
    "triangulate",
    "step2mesh",
]
exclude = [
    "wasm",
]
